USE salesdb;
SELECT * FROM dbo.sales;
-- TOP 5 customers by total sales
SELECT TOP 5
    CUSTOMERNAME,
    FORMAT(SUM(SALES),'C') AS TOTALSALES 
FROM dbo.sales
GROUP BY CUSTOMERNAME
ORDER BY SUM(SALES) DESC;
-- Total sales by year
SELECT
    YEAR_ID,
    FORMAT(SUM(SALES),'C') AS TOTALSALES
FROM dbo.sales
GROUP BY YEAR_ID
ORDER BY SUM(SALES) DESC;
-- Total sales by product line
SELECT
    PRODUCTLINE,
    FORMAT(SUM(SALES),'C') AS TOTALSALES 
FROM dbo.sales
GROUP BY PRODUCTLINE
ORDER BY SUM(SALES) DESC;
-- Country with the highest sales
SELECT TOP 10
    COUNTRY,
    FORMAT(SUM(SALES),'C') AS TOTALSALES
FROM dbo.sales
GROUP BY COUNTRY
ORDER BY SUM(SALES) DESC;
-- Total shipping status
SELECT 
    STATUS,
    COUNT(STATUS) AS TOTALSTATUS
FROM dbo.sales
GROUP BY STATUS
ORDER BY SUM(SALES) DESC;